### ISSUE TITLE
'%' characters in value cause "!(MISSING)" on decrypt

### ISSUE THREAD

**Issue by cmoore-cimpress** [Cimpress-MCP/gosecret#2] opened 2015-03-06 16:18 UTC
If you encrypt a '%' character with gosecret, upon decrypt, the string "(MISSING)" gets inserted into the return value. along with an erroneous leading '!'.

Example: encrypt a string with percent signs:

```
gosecret-cli -mode="encrypt" -keystore="mykeystore" -key="mykey" -value="[gosecret|mysecret|G%a%c%!%K%H%F]"

[gosecret|mysecret|9QsEO/PFYbUcq9NRnKEzS1jAbvRtuxat9QwQ40I=|t0ZvKvHgPcoWGRaX|mykey]
```

decrypt the ciphertext:

```
gosecret-cli -mode="decrypt" -keystore="mykeystore" -value="[gosecret|mysecret|9QsEO/PFYbUcq9NRnKEzS1jAbvRtuxat9QwQ40I=|t0ZvKvHgPcoWGRaX|mykey]"

G%!a(MISSING)%!c(MISSING)%!!(MISSING)%!K(MISSING)%!H(MISSING)%!F(MISSING)
```

**Comment by ryanbreen** [comment] 2015-03-06 16:21
I'll take a look.  Thanks for the report.

**Comment by ryanbreen** [comment] 2015-03-06 19:29
Was this a DOS prompt?  I can't reproduce the issue using config in a file, so I'm wondering if this is introduced by shell-expansion.

**Comment by cmoore-cimpress** [comment] 2015-03-06 19:32
Reproduced both using hiera-gosecret as part of a Vagrant Managed Servers deployment to an Ubuntu 14.04 machine, as well as on the command line in Windows 8.1

**Comment by ryanbreen** [comment] 2015-03-06 19:34
Yeah, % is a special character in both Unix and Windows shells.

I just added a test case dealing with % in files.  It seems to be handled properly if gosecret gets the % as an unadulterated byte stream, as it does when reading from a file.

**Comment by ryanbreen** [comment] 2015-03-06 19:58
Double escaping with %% works on Windows:

```
D:\go32\src\github.com\cimpress-mcp\gosecret>d:\go32\bin\gosecret.exe -mode="encrypt" -keystore="test_keys" -key="myteamkey-2014-09-19" -value="[gosecret|mysecret|G%%a%%c%%!%%K%%H%%F]" > cipher

D:\go32\src\github.com\cimpress-mcp\gosecret>d:\go32\bin\gosecret.exe -mode="decrypt" -keystore="test_keys" cipher
G%a%c%!%K%H%F
```

I'm going to close this, but if there's a bug getting the values into gosecret via hiera-gosecret, we should open a ticket over there.

**Closed by ryanbreen** 2015-03-06 19:58 UTC
